
import NavBar from '@/Components/Shared/NavBar'
import '../globals.css'
import type { Metadata } from 'next'
import { getDictionary } from './Dictionary'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,params
}: {
  children: React.ReactNode,
  params: {lang:string}
}) {

  const lang =params.lang;
  const dict = await getDictionary(lang);

  return (
    <html lang={lang} dir={`${lang === 'en' ? 'ltr' : 'rtl'}`}>
      <body className={`${lang === 'en' ? 'font-Yeseva' : 'font-Yekan'}`}>
      <NavBar data={dict}/>
      <main className="mt-[58px] md:mt-[126px] relative">
        {children}
        </main>
        </body>
    </html>
  )
}
