import Header from '@/Components/Shared/Header'
import '../globals.css'
import type { Metadata } from 'next'
import {Poppins} from 'next/font/google'
import { lazy } from 'react'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const Poppin = Poppins({
  subsets: ['latin']
,
weight:'600'
});
export default function RootLayout({
  children,params
}: {
  children: React.ReactNode,
  params: {lang:string}
}) {

  const lang =params.lang;
  return (
    <html lang={lang} dir={`${lang === 'en' ? 'ltr' : 'rtl'}`}>
      <body className={`${lang === 'en' && Poppin.className}`}>
        <Header lang={lang} />
        {children}</body>
    </html>
  )
}
